/* Safety Tracker v1.0.3 */
const CFG = window.SAFETY_TRACKER_CONFIG || {};
const configured = CFG.supabaseUrl && CFG.supabaseKey && !CFG.supabaseUrl.includes('PASTE_') && !CFG.supabaseKey.includes('PASTE_');
const sb = configured ? window.supabase.createClient(CFG.supabaseUrl, CFG.supabaseKey) : null;

const state = { user:null, profile:null, people:[], documents:[], versions:[], docAssignments:[], docSignoffs:[], training:[], trainingAssignments:[], trainingSignoffs:[], trainingFiles:[] };
const $ = id => document.getElementById(id);
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmtDate = d => d ? new Date(d + (String(d).length===10?'T00:00:00':'' )).toLocaleDateString('en-GB') : '—';
const fmtDateTime = d => d ? new Date(d).toLocaleString('en-GB') : '—';
const todayISO = () => new Date().toISOString().slice(0,10);
const daysFromNow = n => { const d=new Date(); d.setDate(d.getDate()+n); return d.toISOString().slice(0,10); };
const isManager = () => ['admin','manager'].includes(state.profile?.role);
const isAdmin = () => state.profile?.role === 'admin';

function toast(msg){const t=$('toast');t.textContent=msg;t.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.hidden=true,3500)}
function showAuthMessage(msg){$('authMessage').textContent=msg;$('authMessage').hidden=false}
function openModal(title, html){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modal').showModal()}
function closeModal(){$('modal').close()}
function btn(label, cls='secondary', attrs=''){return `<button type="button" class="${cls}" ${attrs}>${esc(label)}</button>`}
function renewalText(value,unit){if(!value||!unit)return 'One-off';return `Every ${value} ${unit.toLowerCase()}`}
function addRenewal(date,value,unit){if(!date||!value||!unit)return null;const d=new Date(date);if(unit==='DAYS')d.setDate(d.getDate()+Number(value));if(unit==='MONTHS')d.setMonth(d.getMonth()+Number(value));if(unit==='YEARS')d.setFullYear(d.getFullYear()+Number(value));return d.toISOString();}
function statusFromDue(due, complete){if(complete && !due)return 'complete';if(!due)return complete?'complete':'due';const now=new Date();const dd=new Date(due);if(dd<now)return 'overdue';return complete?'complete':'due'}

async function init(){
  if(!configured){showAuthMessage('Open config.js and add the separate Safety Tracker Supabase URL and publishable key first.');return;}
  $('loginForm').addEventListener('submit', login);
  $('forgotPasswordBtn').addEventListener('click', forgotPassword);
  $('signOutBtn').addEventListener('click', ()=>sb.auth.signOut());
  $('mainNav').addEventListener('click', e=>{const b=e.target.closest('button[data-view]');if(b)showView(b.dataset.view)});
  $('newDocumentBtn').addEventListener('click', showNewDocument);
  $('newTrainingBtn').addEventListener('click', showNewTraining);
  $('inviteUserBtn').addEventListener('click', showInviteUser);
  $('backupBtn').addEventListener('click', downloadBackup);
  ['documentSearch','documentTypeFilter','documentStatusFilter'].forEach(id=>$(id).addEventListener('input',renderDocuments));
  ['trainingSearch','trainingTypeFilter'].forEach(id=>$(id).addEventListener('input',renderTraining));
  document.querySelectorAll('[data-report]').forEach(b=>b.addEventListener('click',()=>downloadReport(b.dataset.report)));
  document.body.addEventListener('click', globalClick);

  const {data:{session}}=await sb.auth.getSession();
  if(session) await enterApp(session.user); else showLogin();
  sb.auth.onAuthStateChange(async (event,session)=>{
    if(event==='PASSWORD_RECOVERY' && session){showPasswordReset();return;}
    if(session && (!state.user || state.user.id!==session.user.id)) await enterApp(session.user);
    if(!session){state.user=null;state.profile=null;showLogin()}
  });
  if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{});
}

async function login(e){e.preventDefault();$('authMessage').hidden=true;const {error}=await sb.auth.signInWithPassword({email:$('loginEmail').value.trim(),password:$('loginPassword').value});if(error)showAuthMessage(error.message)}
async function forgotPassword(){const email=$('loginEmail').value.trim();if(!email)return showAuthMessage('Enter your email address first.');const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});showAuthMessage(error?error.message:'Password reset email sent.');}
function showPasswordReset(){openModal('Set new password',`<div class="stack"><label>New password<input id="newPassword" type="password" minlength="8"></label><div class="actions">${btn('Save password','primary','id="saveNewPassword"')}</div></div>`)}
async function enterApp(user){state.user=user;const {data,error}=await sb.from('profiles').select('*').eq('id',user.id).single();if(error||!data){showAuthMessage('Profile not found. Ask an administrator to check the Safety Tracker profile.');await sb.auth.signOut();return;}if(data.active===false){showAuthMessage('This Safety Tracker account is disabled.');await sb.auth.signOut();return;}state.profile=data;await loadAll();$('authView').hidden=true;$('appView').hidden=false;$('currentUserName').textContent=data.display_name||user.email;$('currentUserRole').textContent=data.role;document.querySelectorAll('.manager-only').forEach(el=>el.hidden=!isManager());document.querySelectorAll('.admin-only').forEach(el=>el.hidden=!isAdmin());showView('mySafety');}
function showLogin(){$('appView').hidden=true;$('authView').hidden=false}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));document.querySelectorAll('#mainNav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$(name+'View').classList.add('active-view');if(name==='mySafety')renderMySafety();if(name==='documents')renderDocuments();if(name==='training')renderTraining();if(name==='people')renderPeople();if(name==='reports')renderReports();}

async function loadAll(){
  const tables=['profiles','documents','document_versions','document_assignments','document_signoffs','training_sessions','training_assignments','training_signoffs','training_files'];
  const results=await Promise.all(tables.map(t=>sb.from(t).select('*')));
  const map=['people','documents','versions','docAssignments','docSignoffs','training','trainingAssignments','trainingSignoffs','trainingFiles'];
  results.forEach((r,i)=>{if(r.error)console.warn(tables[i],r.error);state[map[i]]=r.data||[]});
  state.people.sort((a,b)=>(a.display_name||'').localeCompare(b.display_name||''));
  populateFilters();
}
function populateFilters(){const types=[...new Set(state.documents.map(d=>d.doc_type))].sort();$('documentTypeFilter').innerHTML='<option value="">All types</option>'+types.map(t=>`<option>${esc(t)}</option>`).join('');}
function personName(id){return state.people.find(p=>p.id===id)?.display_name||'Unknown user'}
function currentVersion(docId){return state.versions.find(v=>v.document_id===docId&&v.status==='CURRENT')||state.versions.filter(v=>v.document_id===docId).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))[0]}
function latestDocSignoff(assignment){return state.docSignoffs.filter(s=>s.assignment_id===assignment.id).sort((a,b)=>new Date(b.signed_at)-new Date(a.signed_at))[0]}
function latestTrainingSignoff(assignment){return state.trainingSignoffs.filter(s=>s.training_assignment_id===assignment.id).sort((a,b)=>new Date(b.signed_at)-new Date(a.signed_at))[0]}
function assignmentDue(a,signoff){if(!signoff)return a.due_date?new Date(a.due_date+'T23:59:59').toISOString():new Date().toISOString();return addRenewal(signoff.signed_at,a.renewal_value,a.renewal_unit)}

function renderMySafety(){
  const myDocs=state.docAssignments.filter(a=>a.user_id===state.user.id&&a.active!==false);
  const myTrain=state.trainingAssignments.filter(a=>a.user_id===state.user.id&&a.active!==false);
  const actions=[];const completed=[];
  myDocs.forEach(a=>{const v=state.versions.find(x=>x.id===a.document_version_id);const d=v&&state.documents.find(x=>x.id===v.document_id);if(!d||!v)return;const s=latestDocSignoff(a);const due=assignmentDue(a,s);const needs=!s || (a.renewal_value&&new Date(due)<=new Date());const item={kind:'document',a,d,v,s,due};(needs?actions:completed).push(item)});
  myTrain.forEach(a=>{const t=state.training.find(x=>x.id===a.training_session_id);if(!t)return;const s=latestTrainingSignoff(a);const due=assignmentDue(a,s);const needs=!s || (a.renewal_value&&new Date(due)<=new Date());const item={kind:'training',a,t,s,due};(needs?actions:completed).push(item)});
  const overdue=actions.filter(x=>x.due&&new Date(x.due)<new Date()).length;
  $('myStats').innerHTML=stat(actions.length,'Actions required')+stat(overdue,'Overdue')+stat(completed.length,'Current')+stat(myDocs.length+myTrain.length,'Assigned');
  $('myActions').innerHTML=actions.length?actions.map(renderMyAction).join(''):'<div class="empty">Nothing outstanding.</div>';
  $('myCompleted').innerHTML=completed.length?completed.map(renderMyAction).join(''):'<div class="empty">No completed records yet.</div>';
}
function stat(n,label){return `<div class="stat"><strong>${n}</strong><span>${esc(label)}</span></div>`}
function renderMyAction(x){
  const overdue=x.due&&new Date(x.due)<new Date();
  if(x.kind==='document')return `<div class="item-card"><div class="row-between"><div><h3>${esc(x.d.title)}</h3><div class="meta"><span>${esc(x.d.doc_type)}</span><span>${esc(x.d.reference||'No reference')}</span><span>Version ${esc(x.v.version_label)}</span></div></div><span class="badge ${overdue?'overdue':x.s?'complete':'due'}">${x.s&&!overdue?'Current':overdue?'Overdue':'Sign-off required'}</span></div><div class="meta"><span>Due: ${x.due?fmtDate(x.due):'One-off complete'}</span><span>${renewalText(x.a.renewal_value,x.a.renewal_unit)}</span></div><div class="row">${btn('View file','secondary',`data-open-doc="${x.v.id}"`)}${(!x.s||overdue)?btn('Acknowledge','primary',`data-sign-doc="${x.a.id}"`):''}</div></div>`;
  return `<div class="item-card"><div class="row-between"><div><h3>${esc(x.t.name)}</h3><div class="meta"><span>${esc(x.t.session_type.replaceAll('_',' '))}</span><span>${fmtDate(x.t.delivered_date)}</span><span>Trainer: ${esc(x.t.trainer_name||'—')}</span></div></div><span class="badge ${overdue?'overdue':x.s?'complete':'due'}">${x.s&&!overdue?'Current':overdue?'Overdue':'Sign-off required'}</span></div><div class="meta"><span>Due: ${x.due?fmtDate(x.due):'One-off complete'}</span><span>${renewalText(x.a.renewal_value,x.a.renewal_unit)}</span></div><div class="row">${btn('View training','secondary',`data-view-training="${x.t.id}"`)}${(!x.s||overdue)?btn('Sign off','primary',`data-sign-training="${x.a.id}"`):''}</div></div>`;
}

function renderDocuments(){
  const q=$('documentSearch').value.toLowerCase();const type=$('documentTypeFilter').value;const status=$('documentStatusFilter').value;
  let docs=state.documents.filter(d=>(!q||`${d.title} ${d.reference||''}`.toLowerCase().includes(q))&&(!type||d.doc_type===type)&&(!status||d.status===status));
  docs.sort((a,b)=>a.title.localeCompare(b.title));
  $('documentsList').innerHTML=docs.length?docs.map(d=>{const v=currentVersion(d.id);const assigns=state.docAssignments.filter(a=>a.document_version_id===v?.id&&a.active!==false);const reviewOverdue=v?.review_date&&v.review_date<todayISO();return `<div class="item-card"><div class="row-between"><div><h3>${esc(d.title)}</h3><div class="meta"><span class="badge">${esc(d.doc_type)}</span><span>${esc(d.reference||'No reference')}</span>${v?`<span>Version ${esc(v.version_label)}</span>`:''}${reviewOverdue?'<span class="badge overdue">Review overdue</span>':''}</div></div><span class="badge">${esc(d.status)}</span></div><div class="meta"><span>Review: ${fmtDate(v?.review_date)}</span><span>${assigns.length} assigned</span><span>${renewalText(d.default_renewal_value,d.default_renewal_unit)}</span></div><div class="row">${v?btn('View file','secondary',`data-open-doc="${v.id}"`):''}${isManager()?btn('Assign','secondary',`data-assign-doc="${d.id}"`)+btn('New version','secondary',`data-new-version="${d.id}"`)+btn('Details','ghost',`data-doc-details="${d.id}"`):btn('Details','ghost',`data-doc-details="${d.id}"`)}</div></div>`}).join(''):'<div class="empty">No documents found.</div>';
}

function showNewDocument(){
  openModal('New document',`<div class="form-grid"><label>Title<input id="docTitle"></label><label>Reference<input id="docRef" placeholder="e.g. RA-014"></label><label>Type<select id="docType"><option>RISK_ASSESSMENT</option><option>COSHH</option><option>SSW</option><option>POLICY</option><option>PROCEDURE</option><option>OTHER</option></select></label><label>Version<input id="docVersion" value="1"></label><label>Issue date<input id="docIssue" type="date" value="${todayISO()}"></label><label>Review date<input id="docReview" type="date"></label><label>Default sign-off frequency<select id="docRenewalPreset"><option value="">One-off only</option><option value="3|MONTHS">Every 3 months</option><option value="6|MONTHS">Every 6 months</option><option value="12|MONTHS">Every 12 months</option><option value="24|MONTHS">Every 24 months</option><option value="CUSTOM">Custom</option></select></label><label>Re-sign on new version<select id="docResign"><option value="true">Yes</option><option value="false">No</option></select></label><div id="docCustomRenewal" class="full" hidden><div class="form-grid"><label>Every<input id="docRenewalValue" type="number" min="1"></label><label>Unit<select id="docRenewalUnit"><option>DAYS</option><option>MONTHS</option><option>YEARS</option></select></label></div></div><label class="full">Upload finished file<input id="docFile" type="file" required></label><label class="full">Notes<textarea id="docNotes"></textarea></label></div><div class="actions">${btn('Cancel','ghost','data-close-modal')}${btn('Create document','primary','id="saveDocument"')}</div>`);
  $('docRenewalPreset').addEventListener('change',()=>{$('docCustomRenewal').hidden=$('docRenewalPreset').value!=='CUSTOM'});
}
function renewalFromPreset(prefix){const p=$(prefix+'RenewalPreset').value;if(!p)return {value:null,unit:null};if(p==='CUSTOM')return {value:Number($(prefix+'RenewalValue').value)||null,unit:$(prefix+'RenewalUnit').value};const [v,u]=p.split('|');return {value:Number(v),unit:u};}
async function saveDocument(){
  const file=$('docFile').files[0];if(!$('docTitle').value.trim()||!file)return toast('Title and file are required.');
  const r=renewalFromPreset('doc');
  const {data:doc,error}=await sb.from('documents').insert({title:$('docTitle').value.trim(),reference:$('docRef').value.trim()||null,doc_type:$('docType').value,status:'ACTIVE',default_renewal_value:r.value,default_renewal_unit:r.unit,resign_on_new_version:$('docResign').value==='true',created_by:state.user.id}).select().single();if(error)return toast(error.message);
  const path=`documents/${doc.id}/${crypto.randomUUID()}-${file.name}`;const up=await sb.storage.from('safety-files').upload(path,file);if(up.error){await sb.from('documents').delete().eq('id',doc.id);return toast(up.error.message)}
  const {error:ve}=await sb.from('document_versions').insert({document_id:doc.id,version_label:$('docVersion').value.trim()||'1',issue_date:$('docIssue').value||null,review_date:$('docReview').value||null,storage_path:path,file_name:file.name,notes:$('docNotes').value.trim()||null,status:'CURRENT',created_by:state.user.id});if(ve)return toast(ve.message);closeModal();await refresh('Document created.');
}

async function showAssignDocument(docId){
  const d=state.documents.find(x=>x.id===docId),v=currentVersion(docId);if(!d||!v)return;const current=state.docAssignments.filter(a=>a.document_version_id===v.id&&a.active!==false).map(a=>a.user_id);const opts=state.people.filter(p=>p.active!==false&&p.role!=='disabled').map(p=>`<label class="check-row"><input type="checkbox" class="assign-person" value="${p.id}" ${current.includes(p.id)?'checked':''}>${esc(p.display_name||p.email)}</label>`).join('');
  openModal('Assign document',`<p><strong>${esc(d.title)}</strong> · Version ${esc(v.version_label)}</p><div class="form-grid"><label>Due date<input id="assignDocDue" type="date" value="${daysFromNow(14)}"></label><label>Sign-off frequency<select id="assignDocRenewalPreset"><option value="DEFAULT">Use document default</option><option value="">One-off only</option><option value="3|MONTHS">Every 3 months</option><option value="6|MONTHS">Every 6 months</option><option value="12|MONTHS">Every 12 months</option><option value="24|MONTHS">Every 24 months</option><option value="CUSTOM">Custom</option></select></label><div id="assignDocCustomRenewal" class="full" hidden><div class="form-grid"><label>Every<input id="assignDocRenewalValue" type="number" min="1"></label><label>Unit<select id="assignDocRenewalUnit"><option>DAYS</option><option>MONTHS</option><option>YEARS</option></select></label></div></div><div class="full"><strong>People</strong><div class="checkbox-list">${opts}</div></div></div><div class="actions">${btn('Cancel','ghost','data-close-modal')}${btn('Save assignments','primary',`data-save-doc-assignment="${docId}"`)}</div>`);
  $('assignDocRenewalPreset').addEventListener('change',()=>{$('assignDocCustomRenewal').hidden=$('assignDocRenewalPreset').value!=='CUSTOM'});
}
async function saveDocAssignments(docId){const d=state.documents.find(x=>x.id===docId),v=currentVersion(docId);const selected=[...document.querySelectorAll('.assign-person:checked')].map(x=>x.value);let rv=d.default_renewal_value,ru=d.default_renewal_unit;const p=$('assignDocRenewalPreset').value;if(p===''){rv=null;ru=null}else if(p==='CUSTOM'){rv=Number($('assignDocRenewalValue').value)||null;ru=$('assignDocRenewalUnit').value}else if(p!=='DEFAULT'){[rv,ru]=p.split('|');rv=Number(rv)}for(const uid of selected){const exists=state.docAssignments.find(a=>a.document_version_id===v.id&&a.user_id===uid);if(!exists){const {error}=await sb.from('document_assignments').insert({document_version_id:v.id,user_id:uid,due_date:$('assignDocDue').value||null,renewal_value:rv,renewal_unit:ru,assigned_by:state.user.id,active:true});if(error)return toast(error.message)}}closeModal();await refresh('Assignments saved.');}

async function showNewVersion(docId){const d=state.documents.find(x=>x.id===docId),old=currentVersion(docId);openModal('Upload new version',`<p><strong>${esc(d.title)}</strong> · Current version ${esc(old?.version_label||'—')}</p><div class="form-grid"><label>New version<input id="newVerLabel"></label><label>Issue date<input id="newVerIssue" type="date" value="${todayISO()}"></label><label>Review date<input id="newVerReview" type="date"></label><label class="full">Upload file<input id="newVerFile" type="file"></label><label class="full">Notes<textarea id="newVerNotes"></textarea></label></div><div class="actions">${btn('Cancel','ghost','data-close-modal')}${btn('Publish version','primary',`data-publish-version="${docId}"`)}</div>`)}
async function publishVersion(docId){const file=$('newVerFile').files[0];if(!$('newVerLabel').value.trim()||!file)return toast('Version and file are required.');const d=state.documents.find(x=>x.id===docId),old=currentVersion(docId);const path=`documents/${docId}/${crypto.randomUUID()}-${file.name}`;const up=await sb.storage.from('safety-files').upload(path,file);if(up.error)return toast(up.error.message);if(old)await sb.from('document_versions').update({status:'SUPERSEDED'}).eq('id',old.id);const {data:nv,error}=await sb.from('document_versions').insert({document_id:docId,version_label:$('newVerLabel').value.trim(),issue_date:$('newVerIssue').value||null,review_date:$('newVerReview').value||null,storage_path:path,file_name:file.name,notes:$('newVerNotes').value.trim()||null,status:'CURRENT',created_by:state.user.id}).select().single();if(error)return toast(error.message);if(d.resign_on_new_version&&old){const oldAssign=state.docAssignments.filter(a=>a.document_version_id===old.id&&a.active!==false);for(const a of oldAssign){await sb.from('document_assignments').insert({document_version_id:nv.id,user_id:a.user_id,due_date:daysFromNow(14),renewal_value:a.renewal_value,renewal_unit:a.renewal_unit,assigned_by:state.user.id,active:true})}}closeModal();await refresh('New version published.');}

function showDocDetails(docId){const d=state.documents.find(x=>x.id===docId);const vs=state.versions.filter(v=>v.document_id===docId).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));openModal('Document details',`<div class="stack"><div><strong>${esc(d.title)}</strong><div class="meta"><span>${esc(d.doc_type)}</span><span>${esc(d.reference||'No reference')}</span></div></div>${vs.map(v=>`<div class="item-card"><div class="row-between"><strong>Version ${esc(v.version_label)}</strong><span class="badge">${esc(v.status)}</span></div><div class="meta"><span>Issued ${fmtDate(v.issue_date)}</span><span>Review ${fmtDate(v.review_date)}</span><span>${esc(v.file_name)}</span></div><div>${btn('View','secondary',`data-open-doc="${v.id}"`)}</div></div>`).join('')}${isManager()?`<div class="actions">${btn(d.status==='ARCHIVED'?'Restore':'Archive',d.status==='ARCHIVED'?'secondary':'danger',`data-toggle-doc="${d.id}"`)}</div>`:''}</div>`)}
async function toggleDocument(id){const d=state.documents.find(x=>x.id===id);await sb.from('documents').update({status:d.status==='ARCHIVED'?'ACTIVE':'ARCHIVED'}).eq('id',id);closeModal();await refresh('Document updated.');}
async function openDocument(versionId){const v=state.versions.find(x=>x.id===versionId);if(!v)return;const {data,error}=await sb.storage.from('safety-files').createSignedUrl(v.storage_path,120);if(error)return toast(error.message);window.open(data.signedUrl,'_blank','noopener');}
async function signDocument(assignmentId){const a=state.docAssignments.find(x=>x.id===assignmentId),v=state.versions.find(x=>x.id===a.document_version_id),d=state.documents.find(x=>x.id===v.document_id);openModal('Acknowledge document',`<p><strong>${esc(d.title)}</strong> · ${esc(d.reference||'')} · Version ${esc(v.version_label)}</p><p>I confirm I have read the assigned document and understand that I should ask my manager if anything is unclear.</p><label class="check-row"><input id="docAckCheck" type="checkbox"> I confirm this acknowledgement.</label><div class="actions">${btn('Cancel','ghost','data-close-modal')}${btn('Acknowledge','primary',`data-confirm-sign-doc="${assignmentId}"`)}</div>`)}
async function confirmSignDocument(id){if(!$('docAckCheck').checked)return toast('Tick the confirmation first.');const a=state.docAssignments.find(x=>x.id===id),v=state.versions.find(x=>x.id===a.document_version_id),d=state.documents.find(x=>x.id===v.document_id);const statement='I confirm I have read the assigned document and understand that I should ask my manager if anything is unclear.';const {error}=await sb.from('document_signoffs').insert({assignment_id:a.id,document_version_id:v.id,user_id:state.user.id,statement_snapshot:statement,title_snapshot:d.title,reference_snapshot:d.reference,version_snapshot:v.version_label});if(error)return toast(error.message);closeModal();await refresh('Acknowledgement recorded.');}

function renderTraining(){const q=$('trainingSearch').value.toLowerCase(),type=$('trainingTypeFilter').value;let rows=state.training.filter(t=>(!q||`${t.name} ${t.description||''}`.toLowerCase().includes(q))&&(!type||t.session_type===type)&&t.status!=='ARCHIVED');rows.sort((a,b)=>new Date(b.delivered_date||b.created_at)-new Date(a.delivered_date||a.created_at));$('trainingList').innerHTML=rows.length?rows.map(t=>{const assigns=state.trainingAssignments.filter(a=>a.training_session_id===t.id&&a.active!==false);const signs=state.trainingSignoffs.filter(s=>assigns.some(a=>a.id===s.training_assignment_id));const done=new Set(signs.map(s=>s.user_id)).size;const reviewOverdue=t.review_date&&t.review_date<todayISO();return `<div class="item-card"><div class="row-between"><div><h3>${esc(t.name)}</h3><div class="meta"><span class="badge">${esc(t.session_type.replaceAll('_',' '))}</span><span>${fmtDate(t.delivered_date)}</span><span>Trainer: ${esc(t.trainer_name||'—')}</span>${reviewOverdue?'<span class="badge overdue">Review overdue</span>':''}</div></div><span class="badge">${done}/${assigns.length} signed</span></div><div class="meta"><span>${renewalText(t.renewal_value,t.renewal_unit)}</span><span>Review: ${fmtDate(t.review_date)}</span></div><div class="row">${btn('View','secondary',`data-view-training="${t.id}"`)}${isManager()?btn('Assign','secondary',`data-assign-training="${t.id}"`)+btn('Archive','ghost',`data-archive-training="${t.id}"`):''}</div></div>`}).join(''):'<div class="empty">No training sessions found.</div>'}
function showNewTraining(){openModal('New training session',`<div class="form-grid"><label>Training name<input id="trainName"></label><label>Type<select id="trainType"><option>AD_HOC</option><option>TOOLBOX_TALK</option><option>INDUCTION</option><option>REFRESHER</option><option>OTHER</option></select></label><label>Date delivered<input id="trainDate" type="date" value="${todayISO()}"></label><label>Trainer / presenter<input id="trainTrainer" value="${esc(state.profile.display_name||'')}"></label><label>Review date<input id="trainReview" type="date"></label><label>Sign-off / refresher frequency<select id="trainRenewalPreset"><option value="">One-off only</option><option value="3|MONTHS">Every 3 months</option><option value="6|MONTHS">Every 6 months</option><option value="12|MONTHS">Every 12 months</option><option value="24|MONTHS">Every 24 months</option><option value="CUSTOM">Custom</option></select></label><div id="trainCustomRenewal" class="full" hidden><div class="form-grid"><label>Every<input id="trainRenewalValue" type="number" min="1"></label><label>Unit<select id="trainRenewalUnit"><option>DAYS</option><option>MONTHS</option><option>YEARS</option></select></label></div></div><label class="full">Details<textarea id="trainDesc"></textarea></label><label class="full">Upload supporting files<input id="trainFiles" type="file" multiple></label></div><div class="actions">${btn('Cancel','ghost','data-close-modal')}${btn('Create training','primary','id="saveTraining"')}</div>`);$('trainRenewalPreset').addEventListener('change',()=>{$('trainCustomRenewal').hidden=$('trainRenewalPreset').value!=='CUSTOM'});}
async function saveTraining(){if(!$('trainName').value.trim())return toast('Training name is required.');const r=renewalFromPreset('train');const {data:t,error}=await sb.from('training_sessions').insert({name:$('trainName').value.trim(),session_type:$('trainType').value,description:$('trainDesc').value.trim()||null,delivered_date:$('trainDate').value||null,trainer_name:$('trainTrainer').value.trim()||null,trainer_user_id:state.user.id,review_date:$('trainReview').value||null,renewal_value:r.value,renewal_unit:r.unit,status:'ACTIVE',created_by:state.user.id}).select().single();if(error)return toast(error.message);for(const file of $('trainFiles').files){const path=`training/${t.id}/${crypto.randomUUID()}-${file.name}`;const up=await sb.storage.from('safety-files').upload(path,file);if(!up.error)await sb.from('training_files').insert({training_session_id:t.id,file_name:file.name,storage_path:path,uploaded_by:state.user.id})}closeModal();await refresh('Training created.');}
function showTrainingDetails(id){const t=state.training.find(x=>x.id===id);const files=state.trainingFiles.filter(f=>f.training_session_id===id);const assigns=state.trainingAssignments.filter(a=>a.training_session_id===id&&a.active!==false);const signed=new Set(state.trainingSignoffs.filter(s=>assigns.some(a=>a.id===s.training_assignment_id)).map(s=>s.user_id));openModal('Training details',`<div class="stack"><div><strong>${esc(t.name)}</strong><div class="meta"><span>${esc(t.session_type.replaceAll('_',' '))}</span><span>${fmtDate(t.delivered_date)}</span><span>Trainer ${esc(t.trainer_name||'—')}</span><span>${renewalText(t.renewal_value,t.renewal_unit)}</span></div></div>${t.description?`<p>${esc(t.description)}</p>`:''}<div><strong>Files</strong><div class="row">${files.length?files.map(f=>btn(f.file_name,'secondary',`data-open-training-file="${f.id}"`)).join(''):'<span class="muted">No supporting files.</span>'}</div></div>${isManager()?`<div><strong>Attendance / sign-off</strong><div class="card-list">${assigns.length?assigns.map(a=>`<div class="row-between"><span>${esc(personName(a.user_id))}</span><span class="badge ${signed.has(a.user_id)?'complete':'due'}">${signed.has(a.user_id)?'Signed':'Outstanding'}</span></div>`).join(''):'<span class="muted">No one assigned.</span>'}</div></div>`:''}</div>`)}
async function openTrainingFile(id){const f=state.trainingFiles.find(x=>x.id===id);if(!f)return;const {data,error}=await sb.storage.from('safety-files').createSignedUrl(f.storage_path,120);if(error)return toast(error.message);window.open(data.signedUrl,'_blank','noopener');}
function showAssignTraining(id){const t=state.training.find(x=>x.id===id);const current=state.trainingAssignments.filter(a=>a.training_session_id===id&&a.active!==false).map(a=>a.user_id);const opts=state.people.filter(p=>p.active!==false).map(p=>`<label class="check-row"><input type="checkbox" class="train-person" value="${p.id}" ${current.includes(p.id)?'checked':''}>${esc(p.display_name||p.email)}</label>`).join('');openModal('Assign training',`<p><strong>${esc(t.name)}</strong></p><div class="form-grid"><label>Complete by<input id="trainAssignDue" type="date" value="${daysFromNow(14)}"></label><div class="full"><strong>People</strong><div class="checkbox-list">${opts}</div></div></div><div class="actions">${btn('Cancel','ghost','data-close-modal')}${btn('Save assignments','primary',`data-save-training-assignment="${id}"`)}</div>`)}
async function saveTrainingAssignments(id){const t=state.training.find(x=>x.id===id);for(const uid of [...document.querySelectorAll('.train-person:checked')].map(x=>x.value)){if(!state.trainingAssignments.find(a=>a.training_session_id===id&&a.user_id===uid)){const {error}=await sb.from('training_assignments').insert({training_session_id:id,user_id:uid,due_date:$('trainAssignDue').value||null,renewal_value:t.renewal_value,renewal_unit:t.renewal_unit,assigned_by:state.user.id,active:true});if(error)return toast(error.message)}}closeModal();await refresh('Training assignments saved.');}
function signTraining(assignmentId){const a=state.trainingAssignments.find(x=>x.id===assignmentId),t=state.training.find(x=>x.id===a.training_session_id);openModal('Training sign-off',`<p><strong>${esc(t.name)}</strong></p><p>I confirm I completed/attended this training and understand that I should ask my manager if anything is unclear.</p><label class="check-row"><input id="trainAckCheck" type="checkbox"> I confirm this sign-off.</label><div class="actions">${btn('Cancel','ghost','data-close-modal')}${btn('Sign off','primary',`data-confirm-sign-training="${assignmentId}"`)}</div>`)}
async function confirmSignTraining(id){if(!$('trainAckCheck').checked)return toast('Tick the confirmation first.');const a=state.trainingAssignments.find(x=>x.id===id),t=state.training.find(x=>x.id===a.training_session_id);const statement='I confirm I completed/attended this training and understand that I should ask my manager if anything is unclear.';const {error}=await sb.from('training_signoffs').insert({training_assignment_id:id,training_session_id:t.id,user_id:state.user.id,statement_snapshot:statement,training_name_snapshot:t.name,trainer_snapshot:t.trainer_name});if(error)return toast(error.message);closeModal();await refresh('Training sign-off recorded.');}
async function archiveTraining(id){await sb.from('training_sessions').update({status:'ARCHIVED'}).eq('id',id);await refresh('Training archived.');}

function renderPeople(){$('peopleList').innerHTML=state.people.length?state.people.map(p=>`<div class="item-card"><div class="row-between"><div><h3>${esc(p.display_name||p.email)}</h3><div class="meta"><span>${esc(p.email||'')}</span><span class="badge">${esc(p.role)}</span></div></div><span class="badge ${p.active===false?'overdue':'complete'}">${p.active===false?'Disabled':'Active'}</span></div>${isAdmin()?`<div class="row">${btn('Set role','secondary',`data-set-role="${p.id}"`)}${p.id!==state.user.id?btn(p.active===false?'Enable':'Disable',p.active===false?'secondary':'danger',`data-toggle-user="${p.id}"`):''}</div>`:''}</div>`).join(''):'<div class="empty">No users.</div>'}
function showInviteUser(){openModal('Invite user',`<div class="form-grid"><label>Name<input id="inviteName"></label><label>Email<input id="inviteEmail" type="email"></label><label>Role<select id="inviteRole"><option value="user">User</option><option value="manager">Manager</option><option value="admin">Admin</option></select></label></div><div class="actions">${btn('Cancel','ghost','data-close-modal')}${btn('Send invite','primary','id="sendInvite"')}</div>`)}
async function sendInvite(){const {data:{session}}=await sb.auth.getSession();const res=await fetch(`${CFG.supabaseUrl}/functions/v1/invite-user`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`,'apikey':CFG.supabaseKey},body:JSON.stringify({action:'invite',email:$('inviteEmail').value.trim(),display_name:$('inviteName').value.trim(),role:$('inviteRole').value,redirect_to:location.origin+location.pathname})});const out=await res.json().catch(()=>({}));if(!res.ok)return toast(out.error||'Invite failed');closeModal();toast('Invitation sent.');}
function showSetRole(id){const p=state.people.find(x=>x.id===id);openModal('Set role',`<label>Role<select id="roleSelect"><option value="user" ${p.role==='user'?'selected':''}>User</option><option value="manager" ${p.role==='manager'?'selected':''}>Manager</option><option value="admin" ${p.role==='admin'?'selected':''}>Admin</option></select></label><div class="actions">${btn('Save','primary',`data-save-role="${id}"`)}</div>`)}
async function saveRole(id){const {data:{session}}=await sb.auth.getSession();const r=await fetch(`${CFG.supabaseUrl}/functions/v1/invite-user`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`,'apikey':CFG.supabaseKey},body:JSON.stringify({action:'set_role',user_id:id,role:$('roleSelect').value})});const o=await r.json().catch(()=>({}));if(!r.ok)return toast(o.error||'Role update failed');closeModal();await refresh('Role updated.');}
async function toggleUser(id){const p=state.people.find(x=>x.id===id);const {data:{session}}=await sb.auth.getSession();const r=await fetch(`${CFG.supabaseUrl}/functions/v1/invite-user`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`,'apikey':CFG.supabaseKey},body:JSON.stringify({action:p.active===false?'enable':'disable',user_id:id})});const o=await r.json().catch(()=>({}));if(!r.ok)return toast(o.error||'User update failed');await refresh('User updated.');}

function reportRows(){
  const doc=[];state.docSignoffs.forEach(s=>{const a=state.docAssignments.find(x=>x.id===s.assignment_id);doc.push({person:personName(s.user_id),email:state.people.find(p=>p.id===s.user_id)?.email||'',type:'Document',title:s.title_snapshot,reference:s.reference_snapshot||'',version:s.version_snapshot,signed_at:s.signed_at,renewal:renewalText(a?.renewal_value,a?.renewal_unit)})});
  const tr=[];state.trainingSignoffs.forEach(s=>{const a=state.trainingAssignments.find(x=>x.id===s.training_assignment_id);tr.push({person:personName(s.user_id),email:state.people.find(p=>p.id===s.user_id)?.email||'',type:'Training',title:s.training_name_snapshot,reference:'',version:'',signed_at:s.signed_at,renewal:renewalText(a?.renewal_value,a?.renewal_unit)})});return {doc,tr};
}
function outstandingRows(){const rows=[];state.docAssignments.filter(a=>a.active!==false).forEach(a=>{const s=latestDocSignoff(a),due=assignmentDue(a,s);if(!s||(a.renewal_value&&new Date(due)<=new Date())){const v=state.versions.find(x=>x.id===a.document_version_id),d=v&&state.documents.find(x=>x.id===v.document_id);if(d)rows.push({person:personName(a.user_id),kind:'Document',item:d.title,reference:d.reference||'',version:v.version_label,due:due})}});state.trainingAssignments.filter(a=>a.active!==false).forEach(a=>{const s=latestTrainingSignoff(a),due=assignmentDue(a,s);if(!s||(a.renewal_value&&new Date(due)<=new Date())){const t=state.training.find(x=>x.id===a.training_session_id);if(t)rows.push({person:personName(a.user_id),kind:'Training',item:t.name,reference:'',version:'',due:due})}});return rows;}
function renderReports(){const out=outstandingRows();const reviews=[...state.versions.filter(v=>v.status==='CURRENT'&&v.review_date),...state.training.filter(t=>t.status==='ACTIVE'&&t.review_date)];$('reportStats').innerHTML=stat(out.length,'Outstanding')+stat(out.filter(r=>r.due&&new Date(r.due)<new Date()).length,'Overdue')+stat(reviews.filter(r=>r.review_date<todayISO()).length,'Reviews overdue')+stat(state.docSignoffs.length+state.trainingSignoffs.length,'Sign-offs recorded');}
function csvEscape(v){return `"${String(v??'').replaceAll('"','""')}"`}
function downloadCSV(name,rows){if(!rows.length)return toast('No rows to export.');const keys=Object.keys(rows[0]);const csv=[keys.map(csvEscape).join(','),...rows.map(r=>keys.map(k=>csvEscape(r[k])).join(','))].join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});downloadBlob(blob,name)}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},500)}
function downloadReport(type){const {doc,tr}=reportRows();if(type==='outstanding')return downloadCSV('safety-outstanding.csv',outstandingRows().map(r=>({...r,due:fmtDateTime(r.due)})));if(type==='document-signoffs')return downloadCSV('document-signoffs.csv',doc.map(r=>({...r,signed_at:fmtDateTime(r.signed_at)})));if(type==='training-signoffs')return downloadCSV('training-signoffs.csv',tr.map(r=>({...r,signed_at:fmtDateTime(r.signed_at)})));if(type==='training-matrix'){const rows=[];state.people.filter(p=>p.active!==false).forEach(p=>state.training.forEach(t=>{const a=state.trainingAssignments.find(x=>x.training_session_id===t.id&&x.user_id===p.id);if(a){const s=latestTrainingSignoff(a);rows.push({person:p.display_name,email:p.email,training:t.name,type:t.session_type,status:s?'Completed':'Outstanding',last_signed:s?fmtDateTime(s.signed_at):'',next_due:s&&a.renewal_value?fmtDateTime(addRenewal(s.signed_at,a.renewal_value,a.renewal_unit)):(a.due_date||'')})}}));return downloadCSV('training-matrix.csv',rows)}if(type==='reviews'){const rows=[];state.versions.filter(v=>v.status==='CURRENT').forEach(v=>{const d=state.documents.find(x=>x.id===v.document_id);rows.push({kind:'Document',title:d?.title||'',reference:d?.reference||'',version:v.version_label,review_date:v.review_date||'',status:v.review_date&&v.review_date<todayISO()?'Overdue':'Current'})});state.training.filter(t=>t.status==='ACTIVE').forEach(t=>rows.push({kind:'Training',title:t.name,reference:'',version:'',review_date:t.review_date||'',status:t.review_date&&t.review_date<todayISO()?'Overdue':'Current'}));return downloadCSV('review-dates.csv',rows)}}
async function downloadBackup(){const payload={exported_at:new Date().toISOString(),profiles:state.people,documents:state.documents,document_versions:state.versions,document_assignments:state.docAssignments,document_signoffs:state.docSignoffs,training_sessions:state.training,training_assignments:state.trainingAssignments,training_signoffs:state.trainingSignoffs,training_files:state.trainingFiles};downloadBlob(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),`safety-tracker-backup-${todayISO()}.json`)}

async function refresh(msg){await loadAll();renderMySafety();renderDocuments();renderTraining();if(isManager()){renderPeople();renderReports()}if(msg)toast(msg)}
async function globalClick(e){const el=e.target.closest('button');if(!el)return;if(el.dataset.closeModal!==undefined)return closeModal();if(el.id==='saveNewPassword'){const {error}=await sb.auth.updateUser({password:$('newPassword').value});if(error)return toast(error.message);closeModal();toast('Password updated.');return}if(el.id==='saveDocument')return saveDocument();if(el.id==='saveTraining')return saveTraining();if(el.id==='sendInvite')return sendInvite();if(el.dataset.openDoc)return openDocument(el.dataset.openDoc);if(el.dataset.signDoc)return signDocument(el.dataset.signDoc);if(el.dataset.confirmSignDoc)return confirmSignDocument(el.dataset.confirmSignDoc);if(el.dataset.assignDoc)return showAssignDocument(el.dataset.assignDoc);if(el.dataset.saveDocAssignment)return saveDocAssignments(el.dataset.saveDocAssignment);if(el.dataset.newVersion)return showNewVersion(el.dataset.newVersion);if(el.dataset.publishVersion)return publishVersion(el.dataset.publishVersion);if(el.dataset.docDetails)return showDocDetails(el.dataset.docDetails);if(el.dataset.toggleDoc)return toggleDocument(el.dataset.toggleDoc);if(el.dataset.viewTraining)return showTrainingDetails(el.dataset.viewTraining);if(el.dataset.openTrainingFile)return openTrainingFile(el.dataset.openTrainingFile);if(el.dataset.assignTraining)return showAssignTraining(el.dataset.assignTraining);if(el.dataset.saveTrainingAssignment)return saveTrainingAssignments(el.dataset.saveTrainingAssignment);if(el.dataset.signTraining)return signTraining(el.dataset.signTraining);if(el.dataset.confirmSignTraining)return confirmSignTraining(el.dataset.confirmSignTraining);if(el.dataset.archiveTraining)return archiveTraining(el.dataset.archiveTraining);if(el.dataset.setRole)return showSetRole(el.dataset.setRole);if(el.dataset.saveRole)return saveRole(el.dataset.saveRole);if(el.dataset.toggleUser)return toggleUser(el.dataset.toggleUser);}

init();
