/* Safety Tracker v2.7.2 - local marketing demo. No Supabase writes. */
'use strict';
(function(){
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const initial=()=>({
    role:'admin',tab:'overview',tourStep:0,
    docs:[
      {id:'ra21',ref:'RA-021',title:'Working at Height',kind:'Risk Assessment',status:'green',label:'Approved / current',issue:'02/09/2026',review:'02/09/2027',method:'Self-training',frequency:'12 months',audience:'Maintenance'},
      {id:'cos14',ref:'COSHH-014',title:'Shower Head Descaling',kind:'COSHH Risk Assessment',status:'amber',label:'Pending approval',issue:'10/09/2026',review:'10/09/2027',method:'Self-training',frequency:'12 months',audience:'Maintenance + Housekeeping',pending:true},
      {id:'ssw6',ref:'SSW-006',title:'Fan Coil Service & Maintenance',kind:'Safe System of Work',status:'green',label:'Approved / current',issue:'04/09/2026',review:'04/09/2027',method:'Instructor-led',frequency:'12 months',audience:'Maintenance'},
      {id:'sds21',ref:'SDS-021',title:'Descaling Chemical Safety Data Sheet',kind:'SDS / MSDS',status:'green',label:'Current reference',issue:'01/08/2026',review:'—',method:'Reference only',frequency:'—',audience:'Linked to COSHH-014'},
      {id:'ra30',ref:'RA-030',title:'Manual Handling – 50 inch Television',kind:'Risk Assessment',status:'red',label:'Review overdue',issue:'15/08/2025',review:'15/08/2026',method:'Self-training',frequency:'12 months',audience:'Maintenance'},
      {id:'tbt9',ref:'TBT-009',title:'Spill Response & Reporting',kind:'Toolbox Talk',status:'amber',label:'Pending approval',issue:'11/09/2026',review:'11/09/2027',method:'Instructor-led',frequency:'On change',audience:'Maintenance + Housekeeping',pending:true}
    ],
    training:[
      {id:'tr1',ref:'POL-TRN-001',title:'Data Protection & GDPR Policy',status:'green',label:'Current',method:'Self-training',frequency:'12 months',audience:'Everyone',complete:'6 / 6'},
      {id:'tr2',ref:'IND-001',title:'Company Safety Induction',status:'amber',label:'1 outstanding',method:'Instructor-led',frequency:'On joining / change',audience:'Everyone',complete:'5 / 6'},
      {id:'tr3',ref:'H&S-REF-004',title:'Fire Safety Refresher',status:'red',label:'2 overdue',method:'Instructor-led',frequency:'12 months',audience:'Front Office + Housekeeping',complete:'4 / 6'}
    ],
    mySafety:[
      {id:'ms1',ref:'RA-021',title:'Working at Height',status:'green',label:'Current',method:'Self-training',due:'02/09/2027',done:true},
      {id:'ms2',ref:'SSW-006',title:'Fan Coil Service & Maintenance',status:'amber',label:'Signature required',method:'Instructor-led',due:'18/09/2026',done:false},
      {id:'ms3',ref:'H&S-REF-004',title:'Fire Safety Refresher',status:'red',label:'Overdue',method:'Instructor-led',due:'05/09/2026',done:false},
      {id:'ms4',ref:'POL-TRN-001',title:'Data Protection & GDPR Policy',status:'green',label:'Current',method:'Self-training',due:'01/09/2027',done:true}
    ],
    people:[
      ['Alex Morgan','Maintenance','User','green','Compliant'],['Jordan Lee','Maintenance','User','amber','1 due'],['Sam Patel','Housekeeping','User','red','1 overdue'],['Taylor Green','Front Office','User','green','Compliant'],['Morgan White','Housekeeping','Manager','amber','2 due'],['Casey Brown','Management','Admin','green','Compliant']
    ],
    awareness:[['Slips, Trips & Falls','green','Current'],['Manual Handling Awareness','amber','Due this month'],['Reporting Hazards','green','Current']],
    ppe:[['Safety footwear','green','Checked'],['Eye protection','green','Checked'],['Disposable gloves','amber','Replacement requested']],
    activity:['COSHH-014 uploaded by Casey Brown','SSW-006 approved by Morgan White','Jordan Lee attended Company Safety Induction','Sam Patel training became overdue','September PPE check opened']
  });
  let st=initial();
  const tabs={
    admin:[['overview','Overview'],['documents','Documents'],['training','Training'],['people','People'],['compliance','Compliance'],['instructor','Instructor'],['reports','Reports'],['help','Help']],
    manager:[['overview','Overview'],['documents','Documents'],['training','Training'],['people','People'],['compliance','Compliance'],['instructor','Instructor'],['reports','Reports'],['help','Help']],
    user:[['mySafety','My Safety'],['awareness','Safety Awareness'],['ppe','PPE Checks'],['help','Help']],
    report:[['reports','Reports']]
  };
  const roleName=r=>({admin:'Admin',manager:'Manager',user:'User',report:'Report Viewer'}[r]||r);
  const defaultTab=r=>r==='user'?'mySafety':r==='report'?'reports':'overview';
  const stat=(n,label,tone='grey')=>`<div class="demo-metric ${tone}"><strong>${esc(n)}</strong><span>${esc(label)}</span></div>`;
  const status=x=>`<span class="demo-status ${x.status}">${esc(x.label)}</span>`;
  const button=(label,action,id='',cls='secondary')=>`<button type="button" class="${cls}" data-demo-action="${action}"${id?` data-demo-id="${esc(id)}"`:''}>${esc(label)}</button>`;

  function enterDemo(){
    st=initial();
    $('authView').hidden=true;$('appView').hidden=true;$('demoView').hidden=false;
    if($('demoRoleSelect'))$('demoRoleSelect').value=st.role;
    render();
    try{history.replaceState(null,'',location.pathname+'?demo=1')}catch{}
  }
  function exitDemo(){location.href=location.pathname;}
  function resetDemo(){const role=st.role,tab=st.tab;st=initial();st.role=role;st.tab=(tabs[role]||[]).some(x=>x[0]===tab)?tab:defaultTab(role);render();toast('Demo reset to its original fictional data.');}
  function toast(msg){const t=$('toast');if(!t)return;t.textContent=msg;t.hidden=false;clearTimeout(window.__demoToast);window.__demoToast=setTimeout(()=>t.hidden=true,2600);}
  function modal(title,body){$('demoModalTitle').textContent=title;$('demoModalBody').innerHTML=body;$('demoModal').hidden=false;}
  function closeModal(){$('demoModal').hidden=true;}
  function renderNav(){
    const nav=$('demoNav');nav.innerHTML=(tabs[st.role]||[]).map(([id,label])=>`<button type="button" data-demo-tab="${id}" class="${st.tab===id?'active':''}">${label}</button>`).join('');
  }
  function render(){renderNav();$('demoRoleSelect').value=st.role;const c=$('demoContent');c.innerHTML=renderTab();}
  function renderTab(){switch(st.tab){case'overview':return overview();case'documents':return documents();case'training':return training();case'people':return people();case'compliance':return compliance();case'instructor':return instructor();case'reports':return reports();case'mySafety':return mySafety();case'awareness':return awareness();case'ppe':return ppe();default:return help();}}
  function overview(){
    const pending=st.docs.filter(x=>x.pending).length, overdue=st.mySafety.filter(x=>x.status==='red').length, due=st.mySafety.filter(x=>x.status==='amber').length;
    return `<div class="demo-hero"><div class="demo-hero-card"><h2>Safety compliance at a glance</h2><p class="muted">This is fictional Example Hotel Ltd data. The same traffic-light rule is used throughout Safety Tracker.</p><div class="stats-grid">${stat(18,'Compliant','green')}${stat(due+3,'Due / action','amber')}${stat(overdue+1,'Overdue / problem','red')}${stat(pending,'Pending approval','amber')}</div><div class="demo-role-summary"><span class="pill">Viewing as ${roleName(st.role)}</span><span class="pill">6 people</span><span class="pill">4 departments</span></div></div><div class="demo-hero-card demo-guide"><h3>60-second guided demo</h3><ol><li>Open <strong>Documents</strong> and approve COSHH-014.</li><li>Its training requirement is created automatically.</li><li>Switch to <strong>User</strong> and complete the new assignment.</li><li>Switch to <strong>Report Viewer</strong> to see the evidence/reporting view.</li></ol>${button('Start guided demo','guide','','primary')}</div></div><div class="demo-section-title"><div><h2>Priority actions</h2><p class="muted">Red first, then amber.</p></div></div><div class="demo-grid">${st.docs.filter(x=>x.status==='red'||x.status==='amber').slice(0,4).map(docCard).join('')}</div>`;
  }
  function docCard(d){return `<article class="demo-record ${d.status}"><div class="demo-meta"><strong>${esc(d.ref)}</strong><span>${esc(d.kind)}</span></div><h3>${esc(d.title)}</h3>${status(d)}<div class="demo-meta"><span>Issue ${esc(d.issue)}</span><span>Review ${esc(d.review)}</span></div><div class="demo-meta"><span>${esc(d.method)}</span><span>${esc(d.frequency)}</span><span>${esc(d.audience)}</span></div><div class="demo-actions">${button('Open document','openDoc',d.id)}${d.pending&&['admin','manager'].includes(st.role)?button('Review & approve','approveDoc',d.id,'primary'):''}</div></article>`;}
  function documents(){return `<div class="demo-section-title"><div><h2>Documents</h2><p class="muted">Controlled RA, COSHH RA, SSW and Toolbox Talk approval drives training. SDS/MSDS remains reference-only.</p></div></div><div class="hint-box"><strong>Approval workflow:</strong> open the exact file → review → confirm audience, Self-training/Instructor-led, due period and refresher frequency → approve. Assignments then activate automatically.</div><div class="demo-grid" style="margin-top:12px">${st.docs.map(docCard).join('')}</div>`;}
  function trainCard(t){return `<article class="demo-record ${t.status}"><div class="demo-meta"><strong>${esc(t.ref)}</strong><span>Standalone training</span></div><h3>${esc(t.title)}</h3>${status(t)}<div class="demo-meta"><span>${esc(t.method)}</span><span>${esc(t.frequency)}</span></div><div class="demo-meta"><span>Audience: ${esc(t.audience)}</span><span>${esc(t.complete)} complete</span></div><div class="demo-actions">${button('Open training','openTraining',t.id)}${['admin','manager'].includes(st.role)?button('Edit audience','showAudience',t.id):''}</div></article>`;}
  function training(){return `<div class="demo-section-title"><div><h2>Standalone Training</h2><p class="muted">For policies, inductions, refreshers and unrelated H&amp;S training. RA/COSHH/SSW training is controlled from Documents instead.</p></div>${button('New standalone training','newTraining','','primary')}</div><div class="demo-grid">${st.training.map(trainCard).join('')}</div>`;}
  function people(){return `<div class="demo-section-title"><div><h2>People</h2><p class="muted">Department membership automatically drives current audience assignments.</p></div></div><div class="demo-grid">${st.people.map((p,i)=>`<article class="demo-record ${p[3]}"><div class="demo-meta"><strong>${esc(p[0])}</strong><span>${esc(p[2])}</span></div><h3>${esc(p[1])}</h3><span class="demo-status ${p[3]}">${esc(p[4])}</span><div class="demo-actions">${button('View compliance','person',String(i))}</div></article>`).join('')}</div>`;}
  function compliance(){const all=[...st.mySafety];return `<div class="demo-section-title"><div><h2>Compliance</h2><p class="muted">Outstanding items are ordered red → amber → green.</p></div></div><div class="stats-grid">${stat(all.filter(x=>x.status==='green').length,'Current','green')}${stat(all.filter(x=>x.status==='amber').length,'Action required','amber')}${stat(all.filter(x=>x.status==='red').length,'Overdue','red')}</div><div class="demo-grid">${all.sort((a,b)=>({red:0,amber:1,green:2}[a.status]-{red:0,amber:1,green:2}[b.status])).map(x=>`<article class="demo-record ${x.status}"><div class="demo-meta"><strong>Alex Morgan</strong><span>Maintenance</span></div><h3>${esc(x.ref)} – ${esc(x.title)}</h3>${status(x)}<div class="demo-meta"><span>${esc(x.method)}</span><span>Due ${esc(x.due)}</span></div></article>`).join('')}</div>`;}
  function instructor(){const items=st.mySafety.filter(x=>x.method==='Instructor-led'&&!x.done);return `<div class="demo-section-title"><div><h2>Instructor</h2><p class="muted">Only outstanding instructor-led work appears here.</p></div></div><div class="demo-grid">${items.map(x=>`<article class="demo-record ${x.status}"><h3>${esc(x.ref)} – ${esc(x.title)}</h3>${status(x)}<div class="demo-meta"><span>Alex Morgan</span><span>Maintenance</span><span>Due ${esc(x.due)}</span></div><div class="demo-actions">${button('Record attendance','attendance',x.id,'primary')}</div></article>`).join('')||'<div class="demo-empty">No outstanding instructor-led work.</div>'}</div>`;}
  function reports(){return `<div class="demo-section-title"><div><h2>Reports</h2><p class="muted">Reporting is read-only in demo mode.</p></div></div><div class="stats-grid">${stat('94%','Training compliance','green')}${stat('2','Overdue','red')}${stat('3','Due soon','amber')}${stat('6','People','grey')}</div><div class="demo-grid"><article class="demo-record green"><h3>Person Evidence Pack</h3><p class="muted">Select a person, then choose the relevant documents and training records for an audit-ready pack.</p><div class="demo-actions">${button('Preview evidence pack','evidence','', 'primary')}</div></article><article class="demo-record grey"><h3>Training Matrix</h3><p class="muted">Current, due and overdue training by person and department.</p><div class="demo-actions">${button('Preview report','report','matrix')}</div></article><article class="demo-record grey"><h3>Document Review Dates</h3><p class="muted">Upcoming and overdue controlled-document reviews.</p><div class="demo-actions">${button('Preview report','report','reviews')}</div></article><article class="demo-record grey"><h3>Activity Log</h3><p class="muted">Who uploaded, reviewed, approved, attended and signed.</p><div class="demo-actions">${button('Preview activity','activity')}</div></article></div>`;}
  function mySafety(){return `<div class="demo-section-title"><div><h2>My Safety</h2><p class="muted">Alex Morgan · Maintenance. The employee only sees what they need.</p></div></div><div class="stats-grid">${stat(st.mySafety.filter(x=>x.status==='green').length,'Current','green')}${stat(st.mySafety.filter(x=>x.status==='amber').length,'Action required','amber')}${stat(st.mySafety.filter(x=>x.status==='red').length,'Overdue','red')}</div><div class="demo-grid">${st.mySafety.sort((a,b)=>({red:0,amber:1,green:2}[a.status]-{red:0,amber:1,green:2}[b.status])).map(x=>`<article class="demo-record ${x.status}"><div class="demo-meta"><strong>${esc(x.ref)}</strong><span>${esc(x.method)}</span></div><h3>${esc(x.title)}</h3>${status(x)}<div class="demo-meta"><span>Due ${esc(x.due)}</span></div><div class="demo-actions">${button('Open safety document','openSafety',x.id)}${!x.done?button(x.method==='Self-training'?'Complete & sign':'Acknowledge / sign','completeSafety',x.id,'primary'):button('View record','viewRecord',x.id)}</div></article>`).join('')}</div>`;}
  function awareness(){return `<div class="demo-section-title"><div><h2>Safety Awareness</h2><p class="muted">Short employee guidance supporting formal training.</p></div></div><div class="demo-grid">${st.awareness.map((x,i)=>`<article class="demo-record ${x[1]}"><h3>${esc(x[0])}</h3><span class="demo-status ${x[1]}">${esc(x[2])}</span>${x[1]!=='green'?`<div class="demo-actions">${button('Read & acknowledge','ackAwareness',String(i),'primary')}</div>`:''}</article>`).join('')}</div>`;}
  function ppe(){return `<div class="demo-section-title"><div><h2>September PPE Check</h2><p class="muted">Check assigned PPE by the 28th and flag anything missing or unsuitable.</p></div></div><div class="demo-grid">${st.ppe.map((x,i)=>`<article class="demo-record ${x[1]}"><h3>${esc(x[0])}</h3><span class="demo-status ${x[1]}">${esc(x[2])}</span></article>`).join('')}</div><div class="demo-toolbar">${button('Submit monthly PPE check','submitPpe','','primary')}</div>`;}
  function help(){return `<div class="demo-section-title"><div><h2>Help</h2><p class="muted">Demo mode follows the same role-based simplicity as the live system.</p></div></div><div class="demo-grid"><article class="demo-record green"><h3>Traffic-light rule</h3><p>Green = current/compliant. Amber = pending/due/action. Red = overdue/problem. Grey = archived/inactive/history.</p></article><article class="demo-record grey"><h3>Controlled documents</h3><p>RA, COSHH RA and SSW training is configured at document approval. No duplicate setup in Training.</p></article><article class="demo-record grey"><h3>Standalone Training</h3><p>Training is for policies, inductions, refreshers and unrelated H&amp;S subjects. It still supports frequency, audience and Self-training/Instructor-led.</p></article><article class="demo-record grey"><h3>Safe demo</h3><p>Nothing in this mode writes to the live database. Reset Demo restores the original fictional data.</p></article></div>`;}

  function act(action,id){
    if(action==='guide'){st.role='manager';st.tab='documents';$('demoRoleSelect').value='manager';render();toast('Step 1: approve the amber COSHH-014 document.');return;}
    if(action==='openDoc'){const d=st.docs.find(x=>x.id===id);return modal(`${d.ref} – ${d.title}`,`<div class="demo-evidence"><strong>Simulated PDF viewer</strong><p>In the live system this opens the exact uploaded PDF. Demo mode never opens or uploads a real company document.</p></div><div class="demo-sim-form" style="margin-top:12px"><div class="demo-field"><span>Status</span>${status(d)}</div><div class="demo-field"><span>Audience</span>${esc(d.audience)}</div><div class="demo-field"><span>Training</span>${esc(d.method)} · ${esc(d.frequency)}</div></div>`);}
    if(action==='approveDoc'){const d=st.docs.find(x=>x.id===id);if(!d)return;return modal('Review & approve',`<p><strong>${esc(d.ref)} – ${esc(d.title)}</strong></p><div class="demo-sim-form"><div class="demo-sim-row"><div class="demo-field"><span>Audience</span>${esc(d.audience)}</div><div class="demo-field"><span>Method</span>${esc(d.method)}</div></div><div class="demo-sim-row"><div class="demo-field"><span>Refresher</span>${esc(d.frequency)}</div><div class="demo-field"><span>Completion due</span>14 days</div></div><div class="demo-field"><span>Digital approval</span>Casey Brown · Admin · Demo signature</div></div><div class="demo-actions">${button('Approve in demo','confirmApprove',id,'primary')}</div>`);}
    if(action==='confirmApprove'){const d=st.docs.find(x=>x.id===id);if(!d)return;d.pending=false;d.status='green';d.label='Approved / current';if(id==='cos14'&&!st.mySafety.some(x=>x.ref==='COSHH-014'))st.mySafety.push({id:'ms-cos14',ref:'COSHH-014',title:'Shower Head Descaling',status:'amber',label:'Training required',method:'Self-training',due:'26/09/2026',done:false});closeModal();render();toast('Approved. Audience training activated automatically.');return;}
    if(action==='openTraining'){const t=st.training.find(x=>x.id===id);return modal(t.title,`<div class="demo-sim-form"><div class="demo-field"><span>Delivery</span>${esc(t.method)}</div><div class="demo-field"><span>Frequency</span>${esc(t.frequency)}</div><div class="demo-field"><span>Audience</span>${esc(t.audience)}</div></div>`);}
    if(action==='showAudience'){const t=st.training.find(x=>x.id===id);return modal('Audience',`<p><strong>${esc(t.title)}</strong></p><div class="demo-field"><span>Current audience</span>${esc(t.audience)}</div><p class="muted">Live mode supports Everyone, one or more Departments and/or specific People.</p>`);}
    if(action==='newTraining'){return modal('New standalone training',`<p>This is the upload flow for policies, inductions and unrelated H&amp;S training.</p><div class="demo-sim-form"><div class="demo-field"><span>Training file</span>Example Policy.pdf</div><div class="demo-sim-row"><div class="demo-field"><span>Delivery</span>Self-training / Instructor-led</div><div class="demo-field"><span>Frequency</span>On change / days / months / years</div></div><div class="demo-field"><span>Who needs this?</span>Everyone / Departments / specific People</div><div class="demo-field"><span>Completion due</span>Set at creation</div></div><div class="demo-actions">${button('Add fictional example','addTraining','', 'primary')}</div>`);}
    if(action==='addTraining'){if(!st.training.some(x=>x.ref==='POL-TRN-005'))st.training.unshift({id:'tr5',ref:'POL-TRN-005',title:'New Lone Working Policy',status:'amber',label:'Assigned / awaiting completion',method:'Self-training',frequency:'12 months',audience:'Maintenance',complete:'0 / 2'});closeModal();render();toast('Fictional standalone training added locally.');return;}
    if(action==='person'){const p=st.people[Number(id)];return modal(`${p[0]} – Compliance`,`<div class="demo-field"><span>Department</span>${esc(p[1])}</div><div class="demo-field" style="margin-top:8px"><span>Current status</span><span class="demo-status ${p[3]}">${esc(p[4])}</span></div>`);}
    if(action==='attendance'){const x=st.mySafety.find(x=>x.id===id);if(x){x.label='Employee signature required';x.status='amber';}render();toast('Attendance recorded. Employee acknowledgement remains outstanding.');return;}
    if(action==='evidence')return modal('Person Evidence Pack',`<div class="demo-evidence"><strong>Alex Morgan · Maintenance</strong><p>Selected evidence: RA-021, SSW-006, training attendance/signatures, PPE check and activity history.</p></div><p class="muted">The live system generates the pack from reporting data. Demo mode does not create or download a real evidence file.</p>`);
    if(action==='report')return modal(id==='matrix'?'Training Matrix':'Document Review Dates',`<p class="muted">This is a simulated report preview. Live reports are generated from the current controlled data and can be exported.</p><div class="stats-grid">${stat('94%','Compliant','green')}${stat('2','Overdue','red')}${stat('3','Due soon','amber')}</div>`);
    if(action==='activity')return modal('Activity Log',`<div class="card-list">${st.activity.map(x=>`<div class="demo-field">${esc(x)}</div>`).join('')}</div>`);
    if(action==='openSafety'||action==='viewRecord')return modal('Safety record',`<div class="demo-evidence"><strong>Approved safety information</strong><p>The employee can reopen the current approved document and their completion evidence here.</p></div>`);
    if(action==='completeSafety'){const x=st.mySafety.find(x=>x.id===id);if(x){x.done=true;x.status='green';x.label='Current';x.due='12/09/2027';}render();toast('Demo acknowledgement recorded locally.');return;}
    if(action==='ackAwareness'){const x=st.awareness[Number(id)];if(x){x[1]='green';x[2]='Current';}render();toast('Awareness acknowledgement completed locally.');return;}
    if(action==='submitPpe'){st.ppe=st.ppe.map(x=>[x[0],'green',x[0]==='Disposable gloves'?'Replacement requested / logged':'Checked']);render();toast('Demo PPE check submitted.');return;}
  }

  function bind(){
    $('tryDemoBtn')?.addEventListener('click',enterDemo);
    $('demoExitBtn')?.addEventListener('click',exitDemo);
    $('demoResetBtn')?.addEventListener('click',resetDemo);
    $('demoModalClose')?.addEventListener('click',closeModal);
    $('demoModal')?.addEventListener('click',e=>{if(e.target===$('demoModal'))closeModal();});
    $('demoRoleSelect')?.addEventListener('change',e=>{st.role=e.target.value;st.tab=defaultTab(st.role);render();});
    $('demoNav')?.addEventListener('click',e=>{const b=e.target.closest('[data-demo-tab]');if(!b)return;st.tab=b.dataset.demoTab;render();});
    $('demoContent')?.addEventListener('click',e=>{const b=e.target.closest('[data-demo-action]');if(!b)return;act(b.dataset.demoAction,b.dataset.demoId||'');});
    $('demoModalBody')?.addEventListener('click',e=>{const b=e.target.closest('[data-demo-action]');if(!b)return;act(b.dataset.demoAction,b.dataset.demoId||'');});
    if(new URLSearchParams(location.search).get('demo')==='1')enterDemo();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
  window.SafetyTrackerDemo={enter:enterDemo,reset:resetDemo,version:'2.7.2'};
})();
